# Generated by Django 4.2.5 on 2023-09-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='atulmodel',
        ),
    ]
